### ISSUE TITLE
Registration tab content

### ISSUE THREAD

**Issue by aanjhan** [sarohan/c2c-ctf-2025#10]
**Eligibility**

Participants must meet the following eligibility criteria to participate in the C2C CTF 2025 competition:

- Participants must be currently enrolled in a university at the time of the qualifier, February 2025.
- Participants must be 18 years of age or older.
- Students who graduate after February 2025 but before the final event in July may still participate.
- Northeastern University must comply with all U.S. federal regulations, including those under the Office of Foreign Assets Control (OFAC) administered by the U.S. Department of Treasury, which enforces economic and trade sanctions against specific countries. Some restrictions may apply to applicants from comprehensively sanctioned countries.

**Registration Rules**

- Participants must register using their university email before the registration deadline.
- Confirmation of registration will be sent to participants who are selected for the final event.
- The username and password will be your access information for the qualifiers and the final in-person event.
- Registering multiple times (e.g., using different email addresses) is prohibited and will result in disqualification.
- Registration rights cannot be transferred to another individual.

_If participants are found to violate these rules, they will be disqualified from the final event and any associated prizes._

After this the big Register button!

**Comment by manavbjain** [comment]
Done
