### ISSUE TITLE
FAQ tab content

### ISSUE THREAD

**Issue by aanjhan** [sarohan/c2c-ctf-2025#11]
# Frequently Asked Questions (FAQs)

### 1. Who is eligible to participate in the competition?
Participants must be currently enrolled in a university at the time of the qualifier (February 2025). They must be 18 years or older and apply using their university email before the registration deadline. Students who graduate after Feb 2025 but before the finals are still eligible. Applicants from comprehensively sanctioned countries may face restrictions due to U.S. federal regulations.

---

### 2. What are the key differences between the qualifier and the final event?
The **qualifier** is an **individual, remote** event where participants compete independently. The **finals** are **team-based and held in-person** at Northeastern University between July 6-9, 2025. Teams of five will be assigned by the organizers.

---

### 3. How will the teams be formed for the finals?
Teams will be formed by the organizers to ensure a diverse mix of skills, backgrounds, and capabilities. Each team will consist of five participants selected from the qualifier. Team leaders will also be designated by the organizers. Participants cannot choose their teammates, as the focus is on fostering collaboration among individuals with varied expertise.

---

### 4. Can I register using a non-university email address?
No, participants must register using their university email address. The same email must be used for all subsequent competition communications, including registering on the competition platform for the finals.

---

### 5. Can I transfer my registration to someone else if I can’t participate?
No, registrations are non-transferable. Only the individual who registered and meets the eligibility criteria may participate.

---

### 6. What should I bring to the in-person finals?
Participants must bring their own laptops and necessary peripherals (e.g., chargers, adapters). Internet access and power outlets will be provided at the venue. Personal travel expenses are the participant's responsibility, but accommodation and meals will be provided during the event.

---

### 7. What happens if I violate the ethics or rules during the competition?
Violations, such as collusion, cheating, or unauthorized attacks, will result in penalties, including point deductions, disqualification, and potential notification of your university. The organizers reserve the right to take further action to maintain the competition’s integrity.

---

### 8. Will there be any support during the competition?
Yes, participants will have access to support:
- For the **qualifier**, a virtual helpdesk channel using Discord will be set up.
- For the **finals**, on-site support will address any technical or logistical issues.

---

### 9. Are there any costs involved in participating?
- **Qualifier:** Participants must cover their own costs, such as internet access and equipment.
- **Finals:** Travel expenses are the responsibility of participants unless otherwise specified. However, accommodation and meals will be provided.

---

### 10. Can the rules change during the competition?
Yes, rules and policies are subject to change. Participants will be notified promptly of any updates and reminded of relevant rules at each stage of the competition.

**Comment by manavbjain** [comment]
Done
