### ISSUE TITLE
Home page content

### ISSUE THREAD

**Issue by aanjhan** [sarohan/c2c-ctf-2025#7]
Home:

C2C image with INCS-CoE 
![](https://c2c-ctf-2024.ecusdf.org/images/c2c-ctf-24.jpg)

A premier Capture-the-flag event!

The Country to Country CTF (C2C) Cybersecurity Challenge is a series of international CTF competitions organized by the International Cyber Security – Center of Excellence (INCS-CoE) with leading international universities. The 2025 competition is hosted by Northeastern University.

C2C is an exciting opportunity for students to work together as international teams to solve interesting CTF challenges, learn new skills, socialize, and promote international collaboration and friendship. Interested university students across the US, UK, France, Israel, Japan, and Australia participated in the qualifying competition on Feb 7 (10 PM ET)-9 (10 PM ET), 2025. The final round of team competition will be held in person at Northeastern University, Boston, on July 6 - 10, 2025.

Prizes:
1st placed team: $3000 ($600 per team member)
2nd placed team: $2000 ($400 per team member)
3rd placed team: $1250 ($250 per team member)

Important Dates:
Registration opens -- 18 December 2024
Registration closes -- Feb 1, 2025
Qualifiers (remote) -- Feb 7 (10 PM ET) to Feb 9 (10 PM ET) (if there is a way to have a link to timeanddate.com so that people can click and find out what this is in their local time, it would be great)
Qualifiers Results -- Feb 20, 2025
Finals (in person in Boston, USA) - July 6 - 9, 2025

**Comment by manavbjain** [comment]
Done
