### ISSUE TITLE
Competition Format Tab content

### ISSUE THREAD

**Issue by aanjhan** [sarohan/c2c-ctf-2025#9]
**Competition Rules**

Qualifier:

- The qualifier is an individual event. Each participant competes independently to solve challenges.
- Participants must provide their appropriate internet connection, IT equipment, and other necessary resources to participate in the qualifier.

Finals (In-Person, Team-based):

- The final is a team-based event. Teams will consist of five individuals assigned by the organizers.
- The finals will be held in-pson at Northeastern Univin persontween July 6-9, 2025. Detailed venue infor and ation and accommodations will be shared in advance.
- Participants are responsible for their travel. 
- Accommodation and meals will be provided during the in-person finals.
- Competitors must bring their own laptops and peripherals for use during the competition. Internet and power outlets will be provided on-site.

 **Team Structure**

- Final event teams will be created by the organizers to ensure diversity, inclusion, and a balance of skills and capabilities.
- Each team will consist of five participants.
- Team leaders will be designated by the organizers.
- Team names must adhere to appropriate standards; offensive or inappropriate names will not be accepted.

**Ethics and Code of Conduct**

All participants must adhere to the highest standards of ethics and fair play. The following actions are strictly prohibited:

- Interfering with, obstructing, or disturbing other teams, participants, or event organizers.
- Spying on or colluding with other teams or participants.
- Providing or seeking hints, clues, or answers from participants outside of your own team.
- Participating in multiple teams.
- Engaging in any unauthorized attacks on networks, systems, or infrastructure.

Violations of these rules may result in point deductions, disqualification, or notification of the participant’s university. In all cases, the organizers reserve the right to take appropriate actions to maintain the event's integrity.

_Rules and policies are subject to change. Participants will be notified of any updates and provided with timely reminders about relevant rules at each stage of the competition._

**Comment by manavbjain** [comment]
Done
